name: Update Homebrew Formula
on:
  release:
    types: [published]
jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Calculate SHA256
        id: sha
        run: |
          curl -L ${{ github.event.release.tarball_url }} | shasum -a 256 | cut -d ' ' -f 1 > sha.txt
          echo "sha256=$(cat sha.txt)" >> $GITHUB_OUTPUT
      
      - name: Checkout tap repository
        uses: actions/checkout@v3
        with:
          repository: yourusername/homebrew-yourtap
          token: ${{ secrets.TAP_REPO_TOKEN }}
      
      - name: Update formula
        run: |
          sed -i 's|url ".*"|url "${{ github.event.release.tarball_url }}"|' Formula/hello.rb
          sed -i 's|sha256 ".*"|sha256 "${{ steps.sha.outputs.sha256 }}"|' Formula/hello.rb
          sed -i 's|version ".*"|version "${{ steps.release.outputs.version }}"|' Formula/hello.rb
      
      - name: Commit and push
        run: |
          git config user.name ${{ secrets.github_username }}
          git config user.email ${{ secrets.github_email }}
          git add Formula/yourformula.rb
          git commit -m "Update formula to ${{ steps.release.outputs.version }}"
          git push
